name: Release

on:
  release:
    types: [created]

jobs:
  release-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.17.5.linux-amd64.tar.gz"
          binary_name: "yahoo"
          project_path: "cmd/yahoo"
          ldflags: "-X main.version=${{ github.event.release.tag_name }}"
          extra_files: LICENSE README.md
